

server:
  port: 8085
spring:
  application:
    name: spring-data-jpa-sample
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpadb?autoReconnect=true&useSSL=false
    username: root
    password: root
   
       
  profiles:
    active:
      - mysql
      
    






    