spring:      
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop #create-drop enable it if need to create DDL for the first time
    show-sql: true
  cache:
    type: redis    
  redis:
    host: localhost
    port: 6379